# Generated by Django 4.0.4 on 2022-04-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('nombreMascota', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.CharField(choices=[('Joven', 'Joven'), ('Adulto', 'Adulto')], default='Joven', max_length=50)),
                ('tamano', models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Pequeño', max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Buscado', 'Buscado'), ('Encontrado', 'Encontrado'), ('Adoptar', 'Adoptar'), ('Cruzar', 'Cruzar')], default='Buscado', max_length=50)),
                ('collar', models.BooleanField(default=False)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('genero', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='Macho', max_length=50)),
                ('visto', models.IntegerField()),
                ('reencuentro', models.BooleanField(default=False)),
                ('contacto', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('foto', models.ImageField(upload_to='posts/images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['autor'],
            },
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('autor', 'nombreMascota', 'raza', 'edad', 'estado'), name='Perro unico'),
        ),
    ]
