# Generated by Django 4.0.4 on 2022-04-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['fecha', 'titulo'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveConstraint(
            model_name='post',
            name='Perro unico',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='id_autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='color',
            new_name='id_mascota',
        ),
        migrations.RemoveField(
            model_name='post',
            name='collar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='post',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='post',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='post',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nombreMascota',
        ),
        migrations.RemoveField(
            model_name='post',
            name='raza',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tamano',
        ),
        migrations.AddField(
            model_name='post',
            name='subTitulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='visto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('id_autor', 'id_mascota', 'estado'), name='Post unico'),
        ),
    ]
