# Generated by Django 4.0.4 on 2022-05-01 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_alter_mascota_color'),
        ('autores', '0001_initial'),
        ('posts', '0002_alter_post_options_remove_post_perro unico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autores.autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota'),
        ),
    ]
