# Generated by Django 4.0.4 on 2022-04-29 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], default='Perro', max_length=50)),
                ('nombreMascota', models.CharField(max_length=80)),
                ('razaPerro', models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Akita', 'Akita'), ('Beagle', 'Beagle'), ('Border Collie', 'Border Collie'), ('Border Terrier', 'Border Terrier'), ('Bulldog', 'Bulldog'), ('Callejero', 'Callejero'), ('Caniche', 'Caniche'), ('Chihuahua', 'Chihuahua'), ('Cruza', 'Cruza'), ('Dalmata', 'Dalmata'), ('Doverman', 'Doverman'), ('Golden Retriever', 'Golden Retriever'), ('Labrador Retriever', 'Labrador Retriever'), ('Mastin', 'Mastin'), ('Pitbull', 'Pitbull'), ('Poodle', 'Poodle'), ('Rottweiler', 'Rottweiler'), ('Salchicha', 'Salchicha'), ('Shih Tzu', 'Shih Tzu'), ('Yorkshire Terrier', 'Yorkshire Terrier')], default='Seleccionar', max_length=80)),
                ('razaGato', models.CharField(choices=[('Seleccionar', 'Seleccionar'), ('Abinisio', 'Abinisio'), ('Angora', 'Angora'), ('Bengala', 'Bengala'), ('Birmano', 'Birmano'), ('Bombay', 'Bombay'), ('Burmilla', 'Burmilla'), ('Cacatua', 'Cacatua'), ('Ceiba', 'Ceiba'), ('Cejas', 'Cejas'), ('Comun', 'Comun'), ('Esfinge', 'Esfinge'), ('Siberiano', 'Siberiano'), ('Himalayo', 'Himalayo'), ('Javanés', 'Javanés'), ('Korat', 'Korat'), ('Laika', 'Laika'), ('Maine', 'Maine'), ('Persa', 'Persa'), ('Ragdoll', 'Ragdoll'), ('Siamés', 'Siamés'), ('Siberiano', 'Siberiano'), ('Sphynx', 'Sphynx'), ('Tibetano', 'Tibetano'), ('Van Turco', 'Van Turco')], default='Seleccionar', max_length=80)),
                ('edad', models.CharField(choices=[('Joven', 'Joven'), ('Adulto', 'Adulto')], default='Joven', max_length=50)),
                ('tamano', models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Pequeño', max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('collar', models.BooleanField(default=False)),
                ('genero', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='Macho', max_length=50)),
                ('foto', models.ImageField(upload_to='mascotas/images')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autores.autor')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['nombreMascota', 'edad'],
            },
        ),
        migrations.AddConstraint(
            model_name='mascota',
            constraint=models.UniqueConstraint(fields=('id_autor', 'nombreMascota', 'edad'), name='Mascota unica'),
        ),
    ]
