# Generated by Django 4.0.4 on 2022-05-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
